# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ebiznesdckrpb

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_75232c3cb5114b639cde7936da9d5346 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5aa7da5ba0a0465299d4a4b9e9e9c537 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_75232c3cb5114b639cde7936da9d5346 }}/pbajda-ecommerce:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ebiznesdckrpb'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f8cb5c2bb1964b69ae45da25ff26fab3 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_75232c3cb5114b639cde7936da9d5346 }}/pbajda-ecommerce:${{ github.sha }}'