# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ebiznesdckrpb

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e24b8519eb634a1ab317055753a6677c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_93e78de62be34ae3b03e001480c59d3a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e24b8519eb634a1ab317055753a6677c }}/ebiz-azure:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ebiznesdckrpb'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3303700a2cf641c195fae6cce446d221 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e24b8519eb634a1ab317055753a6677c }}/ebiz-azure:${{ github.sha }}'