# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ebiznesdckrpb

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_a0a8f2d2fe884727b322a9e6a2f5b1b7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_921b13f41199477f96b6d7dae2ad6c07 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a0a8f2d2fe884727b322a9e6a2f5b1b7 }}/pbajda-ecommerce:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ebiznesdckrpb'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c50d03e9b83841cc89f29d1a271ffe4f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a0a8f2d2fe884727b322a9e6a2f5b1b7 }}/pbajda-ecommerce:${{ github.sha }}'