# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ebiznesdckrpb

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f6d48a3d625242779808a0fb296d5fac }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8e3d9d2b9fa94c32abf06d771afef5b8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f6d48a3d625242779808a0fb296d5fac }}/e-commenrce-azure:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ebiznesdckrpb'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d9018fd277c64c068cbd446b0a373fe8 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f6d48a3d625242779808a0fb296d5fac }}/e-commenrce-azure:${{ github.sha }}'