# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - EbiznesDckr

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_02119730f8e44de485941925a724bcab }}
        password: ${{ secrets.AzureAppService_ContainerPassword_11316b79946a41a9b213a746507ad0db }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_02119730f8e44de485941925a724bcab }}/piotrbajda/pbajda-ecommerce:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EbiznesDckr'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_173265ad4d0d48318fad8883d5edb7b5 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_02119730f8e44de485941925a724bcab }}/piotrbajda/pbajda-ecommerce:${{ github.sha }}'